[package]
name = "rdb-plugin-postgres"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rdb-core.workspace = true
rdb-rdbms-common.workspace = true
rdb-plugin-runtime.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
anyhow.workspace = true
sqlx = { version = "0.7", default-features = false, features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json", "bigdecimal", "macros"] }
